<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <Authors>Chani Pappenheim</Authors>
    <Product>Nudge</Product>
    <Version>1.1.0</Version>
  </PropertyGroup>
</Project>
